version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    directory: "/web"
    schedule:
      interval: "daily"
    directory: "/server"
    schedule:
      interval: "daily"
    directory: "/mobile"
    schedule:
      interval: "daily"
      
  - name: Auto approve/merge Dependabot (native) PR
    uses: Yproximite/auto-approve-and-merge-dependabot-action@v0.1.0

