version: 2
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    directory: "/web"
    schedule:
      interval: "daily"
    directory: "/server"
    schedule:
      interval: "daily"
    directory: "/mobile"
    schedule:
      interval: "daily"
      
