name: Auto approve

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: Yproximite/auto-approve-and-merge-dependabot-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-type: 'minor'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
